@Library('devops-library') _

kaniko_yaml {
    aws_region = "ap-northeast-2"
    language = "python"
    project = "devops"
    namespace = "devops"
    cluster = "eks-main-t"
    domain = "seerslab.io"
    service_url = "GIT_BRANCH-tool.NAMESPACE.CLUSTER.DOMAIN"
    env = "true"
    pre_script = "true"
    containers = [
      [name:"sl-devops-admin", args: ["SONARQUBE=false"]]
    ]
}





